### ISSUE TITLE
Tweet Button Border

### ISSUE THREAD

**Issue by shvam0000** [yashsehgal/twitter-frontend-clone#11]
![image](https://user-images.githubusercontent.com/60486289/116527218-1275d500-a8f8-11eb-8ec5-9cb0e0698f69.png)

The border button is still there when you click on the button.

**Comment by yashsehgal** [comment]
First of all, Thanks for raising this issue - Really appreciate you for this!

Also, I thought that I have already resolved this feature. No issues will work on this.
Would you like to get an assignment on this issue?

**Comment by shvam0000** [comment]
Yeah sure
